/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Connect.SQLServerProvider;
import DAO.DAO_DATHANG;
import DAO.DAO_DATHANG_CT;
import DAO.DAO_HANGHOA;
import DAO.DAO_NHACC;
import Entity.DATHANG;
import Entity.DATHANG_CT;
import Entity.HANGHOA;
import Entity.NHACC;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Hashtable;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author ACER
 */
public class DATHANG_GUI extends javax.swing.JFrame {

    /**
     * Creates new form DATHANG_GUI
     */
    public DATHANG_GUI() {
      initComponents();
         setDefaultCloseOperation(DATHANG_GUI.DISPOSE_ON_CLOSE); 
        this.setLocationRelativeTo(null);
        ngayban();
        HienThi_donDatHang();
        txtMaDonDatHang.enable(false);
        txtNgayDatHang.enable(false);
        load_cbbTenHang();
        load_cbbNhaCungCap();
    }
private void HienThi_donDatHang(){
        DefaultTableModel  dtm1 = new DefaultTableModel();
        String[] tieude1 = {"Mã đơn đặt hàng", "Ngày đặt hàng"};
        dtm1.setColumnIdentifiers(tieude1);
        ArrayList<DATHANG> dshd = DAO_DATHANG.getDATHANG();
        
        for(DATHANG hd:dshd){
            Vector<Object> vec = new Vector<Object>();
                vec.add(hd.getMaDonDatHang());
                vec.add(hd.getNgayDatHang());              
            dtm1.addRow(vec);
        }
        dsDonDatHang.setModel(dtm1);
     }
    private void HienThi_ChiTietDonDatHang(){
        DefaultTableModel dtm2 = new DefaultTableModel();
        String[] tieude2 = {"Mã hàng hóa", "Tên hàng hóa", "Số lượng", "Nhà sản xuất"};
        dtm2.setColumnIdentifiers(tieude2);
        ArrayList<DATHANG_CT> dshd = DAO_DATHANG_CT.getDATHANG_CT(txtMaDonDatHang.getText());
        for (DATHANG_CT hd : dshd) {
            Vector<Object> vec = new Vector<Object>();
            // Lấy thông tin mã hàng, số lượng từ bảng HANGHOA
            HANGHOA hangHoa = DAO_HANGHOA.layHANGHOA(hd.getMaHangHoa());
            vec.add(hangHoa.getMAHANG()); // Thêm mã hàng
            vec.add(hangHoa.getTENHANG()); // Thêm tên hàng
            vec.add(hd.getSoLuong()); // Thêm số lượng

            // Lấy tên nhà sản xuất từ bảng NHACC
            NHACC nhaSx = DAO_NHACC.layNCC(hd.getNcc());
            vec.add(nhaSx.getTenNhacc()); // Thêm tên nhà sản xuất

            dtm2.addRow(vec);
        }
        dsChiTietDonDatHang.setModel(dtm2);
    }
    
    
    private void load_cbbTenHang(){
      dshh =DAO_HANGHOA.getHANGHOA();
        for(HANGHOA hh:dshh)
            cbbTenHang.addItem(hh.getTENHANG());
    }
    
    private void load_cbbNhaCungCap(){
      dsncc =DAO_NHACC.getNHACC();
        for(NHACC hh:dsncc)
            cbbNhaCungCap.addItem(hh.getTenNhacc());
    }
     
    private ArrayList<HANGHOA> dshh;
    private ArrayList<NHACC> dsncc;
    private ArrayList<DATHANG> danhsachDonDatHang;
    private ArrayList<DATHANG_CT> danhsachChiTietDonDatHang;
    private int maHangChon;
     private int maNCC;
    
    private void ngayban()
    {
        Date today = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String todayDateStr = dateFormat.format(today);
        java.sql.Date todayDate = java.sql.Date.valueOf(todayDateStr);
        txtNgayDatHang.setText(todayDateStr);
    }
 
   private void taomaddh() throws SQLException {
   
     SimpleDateFormat sdf = new SimpleDateFormat("MMddss");
        Date currentDate = new Date();
        String maHoaDon = "DH" + sdf.format(currentDate);
       
        String minuteSecond = new SimpleDateFormat("ss").format(currentDate);
      
        if (maHoaDon.length() > 10) {
            maHoaDon = maHoaDon.substring(0, 10);
        }
       
        maHoaDon += minuteSecond;
        
        txtMaDonDatHang.setText(maHoaDon);
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dsChiTietDonDatHang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        dsDonDatHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        cbbTenHang = new javax.swing.JComboBox<>();
        cbbNhaCungCap = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNgayDatHang = new javax.swing.JTextField();
        txtMaDonDatHang = new javax.swing.JTextField();
        btnTaoMoi = new javax.swing.JButton();
        btnInDonDatHang = new javax.swing.JButton();
        btnXoaDonDatHang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dsChiTietDonDatHang.setBackground(new java.awt.Color(204, 255, 204));
        dsChiTietDonDatHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dsChiTietDonDatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dsChiTietDonDatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsChiTietDonDatHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dsChiTietDonDatHang);

        dsDonDatHang.setBackground(new java.awt.Color(204, 255, 204));
        dsDonDatHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dsDonDatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dsDonDatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsDonDatHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dsDonDatHang);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Đặt Hàng");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết đơn đặt hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Số lượng");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Tên hàng");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Nhà cung cấp");

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(0, 153, 0));
        btnXoa.setText("Xóa");
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(0, 153, 0));
        btnThem.setText("Thêm");
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(0, 153, 0));
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 153, 0));
        btnClear.setText("Clear");
        btnClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        cbbTenHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbbTenHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTenHangActionPerformed(evt);
            }
        });

        cbbNhaCungCap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbbNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNhaCungCapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSoLuong)
                    .addComponent(cbbTenHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbNhaCungCap, 0, 212, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin đơn đặt hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Ngày đặt hàng");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Mã đơn đặt hàng");

        txtNgayDatHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtMaDonDatHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnTaoMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTaoMoi.setForeground(new java.awt.Color(0, 153, 0));
        btnTaoMoi.setText("Tạo mới");
        btnTaoMoi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });

        btnInDonDatHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInDonDatHang.setForeground(new java.awt.Color(0, 153, 0));
        btnInDonDatHang.setText("In Đơn Đặt");
        btnInDonDatHang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInDonDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInDonDatHangActionPerformed(evt);
            }
        });

        btnXoaDonDatHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaDonDatHang.setForeground(new java.awt.Color(0, 153, 0));
        btnXoaDonDatHang.setText("Xóa");
        btnXoaDonDatHang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoaDonDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDonDatHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(txtMaDonDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNgayDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addComponent(btnInDonDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTaoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaDonDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaDonDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNgayDatHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInDonDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaDonDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(374, 374, 374))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dsChiTietDonDatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsChiTietDonDatHangMouseClicked
     /* int row = dsChiTietDonDatHang.getSelectedRow();
        txtSoLuong.setText(dsChiTietDonDatHang.getValueAt(row, 2) + ""); 
        cbbTenHang.setSelectedIndex((int) dsChiTietDonDatHang.getValueAt(row, 1)-1);
          cbbNhaCungCap.setSelectedIndex((int) dsChiTietDonDatHang.getValueAt(row, 3)-1);*/
    int row = dsChiTietDonDatHang.getSelectedRow();
    txtSoLuong.setText(dsChiTietDonDatHang.getValueAt(row, 2) + ""); 
    
    // Lấy tên hàng từ JTable
    String tenHang = (String) dsChiTietDonDatHang.getValueAt(row, 1);
    // Lấy tên nhà cung cấp từ JTable
    String tenNhaCungCap = (String) dsChiTietDonDatHang.getValueAt(row, 3);

    // Thiết lập giá trị cho ComboBox của tên hàng
    for (int i = 0; i < cbbTenHang.getItemCount(); i++) {
        if (cbbTenHang.getItemAt(i).equals(tenHang)) {
            cbbTenHang.setSelectedIndex(i);
            break;
        }
    }

    // Thiết lập giá trị cho ComboBox của tên nhà cung cấp
    for (int i = 0; i < cbbNhaCungCap.getItemCount(); i++) {
        if (cbbNhaCungCap.getItemAt(i).equals(tenNhaCungCap)) {
            cbbNhaCungCap.setSelectedIndex(i);
            break;
        }
    }
    }//GEN-LAST:event_dsChiTietDonDatHangMouseClicked

    private void dsDonDatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsDonDatHangMouseClicked
        int row = dsDonDatHang.getSelectedRow();
        txtMaDonDatHang.setText((String)dsDonDatHang.getValueAt(row, 0));
        txtNgayDatHang.setText((String)dsDonDatHang.getValueAt(row, 1));
        HienThi_ChiTietDonDatHang();
    }//GEN-LAST:event_dsDonDatHangMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
         String madh = txtMaDonDatHang.getText();
        String mahang = cbbTenHang.getSelectedItem().toString();
        String tenncc = cbbNhaCungCap.getSelectedItem().toString();

        int maHH = timMaHangTheoTen(mahang);
        int mancc = timMaNhaCungCapTheoTen(tenncc);

        try {
            if (DAO_DATHANG_CT.xoaDATHANG_CT(madh, maHH, mancc)) {
                JOptionPane.showMessageDialog(this, "Xóa chi tiết đơn đặt hàng thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                // Sau khi xóa thành công, cập nhật lại hiển thị danh sách đơn đặt hàng và chi tiết đơn đặt hàng
                HienThi_donDatHang();
                HienThi_ChiTietDonDatHang();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa chi tiết đơn đặt hàng không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DAO_DATHANG_CT.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi xóa chi tiết đơn đặt hàng", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed
     private int timMaHangTheoTen(String tenHang) {
            for (HANGHOA hh : dshh) {
                if (hh.getTENHANG().equals(tenHang)) {
                    return hh.getMAHANG();
                }
            }
            return -1;
        }

        private int timMaNhaCungCapTheoTen(String tenNhaCungCap) {
            for (NHACC ncc : dsncc) {
                if (ncc.getTenNhacc().equals(tenNhaCungCap)) {
                    return ncc.getMaNhacc();
                }
            }
            return -1; 
        }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

       // Lấy dữ liệu từ các thành phần giao diện
        String madh = txtMaDonDatHang.getText();
        String tenhang = cbbTenHang.getSelectedItem().toString();
        String soluong = txtSoLuong.getText();
        String tenncc = cbbNhaCungCap.getSelectedItem().toString(); 

        // Lấy mã hàng và mã nhà cung cấp từ tên tương ứng
        int mahang = timMaHangTheoTen(tenhang);
        int mancc = timMaNhaCungCapTheoTen(tenncc);

        // Khởi tạo biến số lượng với giá trị không hợp lệ
        int SL = -1;
        try {
            // Thử chuyển đổi chuỗi số lượng thành số nguyên
            SL = Integer.parseInt(soluong);
            // Kiểm tra số lượng có phải là số nguyên dương không
            if (SL <= 0) {
                // Hiển thị thông báo lỗi nếu số lượng không hợp lệ
                JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên dương", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return; // Dừng thực thi nếu số lượng không hợp lệ
            }
        } catch (NumberFormatException e) {
            // Hiển thị thông báo lỗi nếu chuỗi không thể chuyển đổi thành số nguyên
            JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên dương", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return; // Dừng thực thi nếu số lượng không hợp lệ
        }

        // Tạo đối tượng chi tiết đơn đặt hàng và thiết lập các thuộc tính
        DATHANG_CT cthd = new DATHANG_CT();
        cthd.setMaDonDatHang(madh);
        cthd.setMaHangHoa(mahang);
        cthd.setSoLuong(SL);
        cthd.setNcc(mancc);

        try {
            // Thêm chi tiết đơn đặt hàng vào cơ sở dữ liệu
            DAO_DATHANG_CT.themDATHANG_CT(cthd);
            // Tải lại các combobox sau khi thêm chi tiết đơn đặt hàng
            load_cbbTenHang();
            load_cbbNhaCungCap();
        } catch (SQLException ex) {
            // Ghi log lỗi và hiển thị thông báo lỗi nếu có lỗi xảy ra khi thêm chi tiết đơn đặt hàng
            Logger.getLogger(HOADON_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Hiển thị thông báo thành công
        JOptionPane.showMessageDialog(this, "Thêm chi tiết hóa đơn thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        // Cập nhật giao diện để hiển thị đơn đặt hàng và chi tiết đơn đặt hàng
        HienThi_donDatHang();
        HienThi_ChiTietDonDatHang();
        // Xóa nội dung trường số lượng
        txtSoLuong.setText("");

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        String maddh = txtMaDonDatHang.getText();
        String tenhang = cbbTenHang.getSelectedItem().toString();
        String soluong = txtSoLuong.getText();
        String tenncc = cbbNhaCungCap.getSelectedItem().toString();

        // Chuyển đổi tên hàng hoá và tên nhà cung cấp thành mã tương ứng
        int mahang = timMaHangTheoTen(tenhang);
        int mancc = timMaNhaCungCapTheoTen(tenncc);

        // Chuyển đổi số lượng từ chuỗi thành số nguyên
        int SL = Integer.parseInt(soluong);

        // Tạo một đối tượng DATHANG_CT để cập nhật
        DATHANG_CT cthd = new DATHANG_CT();
        cthd.setMaDonDatHang(maddh);
        cthd.setMaHangHoa(mahang);
        cthd.setSoLuong(SL);
        cthd.setNcc(mancc);

        try {
            // Gọi phương thức cập nhật từ lớp DAO_DATHANG_CT
            if (DAO_DATHANG_CT.capNhatDATHANG_CT(cthd)) {
                // Nếu cập nhật thành công, thông báo và cập nhật lại dữ liệu trong combobox
                JOptionPane.showMessageDialog(this, "Cập nhật thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                load_cbbTenHang();
                load_cbbNhaCungCap();
                HienThi_ChiTietDonDatHang(); // Cập nhật lại danh sách chi tiết đơn hàng
                 txtSoLuong.setText("");
            } else {
                // Nếu cập nhật không thành công, thông báo lỗi
                JOptionPane.showMessageDialog(this, "Cập nhật không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            // Xử lý ngoại lệ SQL
            Logger.getLogger(DATHANG_GUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi cập nhật", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtSoLuong.setText("");

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiActionPerformed
          try {
            taomaddh();
        } catch (SQLException ex) {
            Logger.getLogger(DATHANG_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        String mahd = txtMaDonDatHang.getText();
        String ngaytao = txtNgayDatHang.getText();
        DATHANG hd = new DATHANG();
        hd.setMaDonDatHang(mahd);
        hd.setNgayDatHang(ngaytao);
        try {
            DAO_DATHANG.themDONDATHANG(hd);
        } catch (SQLException ex) {
            Logger.getLogger(DAO_DATHANG.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        HienThi_donDatHang();

    }//GEN-LAST:event_btnTaoMoiActionPerformed

    private void btnXoaDonDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDonDatHangActionPerformed
        String mahh = txtMaDonDatHang.getText();
        try {
            DAO_DATHANG.xoaDONDATHANG(mahh);
        } catch (SQLException ex) {
            Logger.getLogger(DAO_DATHANG.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "XOa  thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        HienThi_donDatHang();

        txtMaDonDatHang.setText("");
    }//GEN-LAST:event_btnXoaDonDatHangActionPerformed

    private void btnInDonDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInDonDatHangActionPerformed
        // TODO add your handling code here:
      /*  if(txtMaDonDatHang.getText().length()<=0)
            return;
        if(dsDonDatHang.getRowCount()<=0)
            return;
        try{
            Hashtable map= new Hashtable();
            //D:\CN Java\DaAn_test\BT_End_Mon\src\Report\rpHoaDon.jrxml
            //JasperReport rpt= JasperCompileManager.compileReport("D:\\CN Java\\DoAn\\lan4\\BT_End_Mon\\src\\Report\\rpHoaDon.jrxml");
             JasperReport rpt= JasperCompileManager.compileReport("src/Report/rpDH.jrxml");
            map.put("sMADONHANG",txtMaDonDatHang.getText());
            SQLServerProvider provider = new SQLServerProvider();
            java.sql.Connection conn = provider.open(); 
            JasperPrint p = JasperFillManager.fillReport(rpt, map, conn); 
            JasperViewer.viewReport(p,false);

            
        }catch(JRException | SQLException ex){
            Logger.getLogger(HOADON_GUI.class.getName()).log(Level.SEVERE,null, ex);
        }
    */
  if(txtMaDonDatHang.getText().length()<=0)
            return;
        if(dsDonDatHang.getRowCount()<=0)
            return;
        try{
            Hashtable map= new Hashtable();
            //D:\CN Java\DaAn_test\BT_End_Mon\src\Report\rpHoaDon.jrxml
            //JasperReport rpt= JasperCompileManager.compileReport("D:\\Document\\QuanLyNhaSach\\BT_End_Mon\\BT_End_Mon\\src\\Report\\rpHoaDon.jrxml");
             JasperReport rpt= JasperCompileManager.compileReport("src/Report/rpDH.jrxml");
            map.put("sMADONHANG",txtMaDonDatHang.getText());
            SQLServerProvider provider = new SQLServerProvider();
            java.sql.Connection conn = provider.open(); 
            JasperPrint p = JasperFillManager.fillReport(rpt, map, conn); 
            JasperViewer.viewReport(p,false);   
        }catch(JRException | SQLException ex){
            Logger.getLogger(HOADON_GUI.class.getName()).log(Level.SEVERE,null, ex);
        }
    }//GEN-LAST:event_btnInDonDatHangActionPerformed

    private void cbbTenHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTenHangActionPerformed
        // TODO add your handling code here:
      int selectedIndex = cbbTenHang.getSelectedIndex();
        HANGHOA selectedHangHoa = dshh.get(selectedIndex);
        maHangChon = selectedHangHoa.getMAHANG();
        String tenHangChon = selectedHangHoa.getTENHANG();
        System.out.println(maHangChon);
    }//GEN-LAST:event_cbbTenHangActionPerformed

    private void cbbNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNhaCungCapActionPerformed
        // TODO add your handling code here:
    /* int row = dsChiTietDonDatHang.getSelectedRow();
        if (row >= 0) {
            maHangChon = timMaHangTheoTen(dsChiTietDonDatHang.getValueAt(row, 1).toString());
            cbbTenHang.setSelectedItem(dsChiTietDonDatHang.getValueAt(row, 1).toString());
            txtSoLuong.setText(String.valueOf(dsChiTietDonDatHang.getValueAt(row, 2)));
            cbbNhaCungCap.setSelectedItem(dsChiTietDonDatHang.getValueAt(row, 3).toString());
        } else {
            System.err.println("Chỉ số hàng không hợp lệ: " + row);
        }*/
     if (!cbbNhaCungCap.isPopupVisible()) {
        // Lấy hàng được chọn từ bảng
        int row = dsChiTietDonDatHang.getSelectedRow();
        if (row >= 0) {
            maHangChon = timMaHangTheoTen(dsChiTietDonDatHang.getValueAt(row, 1).toString());
            cbbTenHang.setSelectedItem(dsChiTietDonDatHang.getValueAt(row, 1).toString());
            txtSoLuong.setText(String.valueOf(dsChiTietDonDatHang.getValueAt(row, 2)));
            cbbNhaCungCap.setSelectedItem(dsChiTietDonDatHang.getValueAt(row, 3).toString());
        } else {
            // Nếu không có hàng nào được chọn, thông báo lỗi
            System.err.println("Không có hàng nào được chọn.");
        }
    }

    }//GEN-LAST:event_cbbNhaCungCapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DATHANG_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DATHANG_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DATHANG_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DATHANG_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DATHANG_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnInDonDatHang;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaDonDatHang;
    private javax.swing.JComboBox<String> cbbNhaCungCap;
    private javax.swing.JComboBox<String> cbbTenHang;
    private javax.swing.JTable dsChiTietDonDatHang;
    private javax.swing.JTable dsDonDatHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtMaDonDatHang;
    private javax.swing.JTextField txtNgayDatHang;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
