/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Connect.SQLServerProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import GUI.Menu;
import DAO.DAO_NHANVIEN;
import GUI.HOADON_GUI;
import GUI.NHANVIEN_GUI;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author PC
 */
public class Login extends javax.swing.JFrame {
    private SQLServerProvider cn;
    private Connection conn;
    PreparedStatement preparedStatement;
    ResultSet resultSet;
    private int maNV;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
         this.setLocationRelativeTo(null);
        cn = new SQLServerProvider();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDN = new javax.swing.JTextField();
        btnDN = new javax.swing.JButton();
        btnThemTK = new javax.swing.JButton();
        btnQuenMK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JPassworđN = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username.png"))); // NOI18N
        jLabel2.setText("Username:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 123, 42));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 123, -1));

        txtDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNActionPerformed(evt);
            }
        });
        getContentPane().add(txtDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 176, 30));

        btnDN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDN.setForeground(new java.awt.Color(153, 102, 255));
        btnDN.setText("Login");
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });
        getContentPane().add(btnDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 105, -1));

        btnThemTK.setForeground(new java.awt.Color(255, 0, 255));
        btnThemTK.setText("Thêm tài khoản");
        btnThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTKActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 120, -1));

        btnQuenMK.setForeground(new java.awt.Color(0, 153, 51));
        btnQuenMK.setText("Quên mật khẩu");
        btnQuenMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMKActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuenMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nenlogin.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 50, 60));
        getContentPane().add(JPassworđN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 176, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nenNhanvien.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTKActionPerformed
        // TODO add your handling code here:
        Register r=new Register();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThemTKActionPerformed

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        // TODO add your handling code here:
         String user = txtDN.getText().trim();
    String pass = new String(JPassworđN.getPassword()).trim();

    if (user.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không để thông tin trống!");
        return;
    }

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    try {
        conn = cn.open();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Không thể kết nối đến cơ sở dữ liệu.");
            return;
        }

        String sql_dk = "SELECT tk.MANV, nv.TENNV, tk.is_admin FROM TAIKHOAN tk INNER JOIN NHANVIEN nv ON tk.MANV = nv.MANV WHERE tk.TENTAIKHOAN = ? AND tk.MATKHAU = ?";
        ps = conn.prepareStatement(sql_dk);
        ps.setString(1, user);
        ps.setString(2, pass);

        rs = ps.executeQuery();
        if (rs.next()) {
            int manv = rs.getInt("MANV");
            String tenNV = rs.getString("TENNV");
            int isAdmin = rs.getInt("is_admin");

            Menu menuFrame = new Menu(tenNV, String.valueOf(manv), isAdmin);
            menuFrame.setVisible(true);

            this.dispose();
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc mật khẩu!");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi đăng nhập: " + e.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            if (conn != null) conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
        

        /***************************************************************************************/ 
    /*
       String user = txtDN.getText().trim();
        String pass = JPassworđN.getText().trim();
        System.out.println("Username: " + user); 
        System.out.println("Password: " + pass);

        if (user.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không để thông tin trống!");
            return;
        }

        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            conn = cn.open();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Không thể kết nối đến cơ sở dữ liệu.");
                return;
            }

            String sql_dk = "SELECT * FROM TAIKHOAN WHERE TENTAIKHOAN = ? AND MATKHAU = ?";
            ps = conn.prepareStatement(sql_dk);
            ps.setString(1, user);
            ps.setString(2, pass);

            rs = ps.executeQuery();
            if (rs.next()) {
                String tentaikhoan = rs.getString("TENTAIKHOAN");
            // Kiểm tra là admin không
                boolean isAdmin = tentaikhoan.equals("admin");
                if (isAdmin) { 
                Menu m=new Menu();
                m.setVisible(true);
            } else {
                Menu m=new Menu();
                m.setVisible(true);
                m.hideNhanVienMenuItem(); // Ẩn chức năng nhân viên
            }
                
                this.dispose();
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc mật khẩu!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi đăng nhập: " + e.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        */
    

    }//GEN-LAST:event_btnDNActionPerformed

    private void btnQuenMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuenMKActionPerformed
        // TODO add your handling code here:
        QuenMatKhau q=new QuenMatKhau();
        q.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuenMKActionPerformed

    private void txtDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPassworđN;
    private javax.swing.JButton btnDN;
    private javax.swing.JButton btnQuenMK;
    private javax.swing.JButton btnThemTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDN;
    // End of variables declaration//GEN-END:variables
}
