/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class Menu extends javax.swing.JFrame {
   //private boolean isAdmin;
    /**
     * Creates new form Menu
     */
   private String tenNhanVien;
    private boolean isAdmin;
    private String maNhanVien;

    public Menu() {
        initComponents();
    }

    // Ẩn danh mục nhân viên
    public void hideNhanVienMenuItem() {
        jMenuItemNV.setVisible(false); 
    }

    public Menu(String tenNV, String maNV, int isAdmin) {
        this.tenNhanVien = tenNV;
        this.maNhanVien = maNV;
        this.isAdmin = (isAdmin == 0); // isAdmin = 0 là admin, = 1 không phải admin
        initComponents();
        lblTenNV.setText(tenNV);
        if (!this.isAdmin) {
            hideNhanVienMenuItem();
        }
    }
  
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblTenNV = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemHH = new javax.swing.JMenuItem();
        jMenuItemLoai = new javax.swing.JMenuItem();
        jMenuDatHang = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemNV = new javax.swing.JMenuItem();
        jMenuItemKH = new javax.swing.JMenuItem();
        jMenuItemDT = new javax.swing.JMenuItem();
        jMenuItemHD = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("QUẢN LÝ NHÀ SÁCH");

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 204, 0));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jMenu1.setBackground(new java.awt.Color(204, 255, 255));
        jMenu1.setForeground(new java.awt.Color(0, 51, 255));
        jMenu1.setText("SẢN PHẨM");

        jMenuItemHH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemHH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hh.png"))); // NOI18N
        jMenuItemHH.setText("SÁCH");
        jMenuItemHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHHActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemHH);

        jMenuItemLoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loai.jpg"))); // NOI18N
        jMenuItemLoai.setText("LOẠI");
        jMenuItemLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoaiActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLoai);

        jMenuDatHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuDatHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dathang.png"))); // NOI18N
        jMenuDatHang.setText("ĐẶT HÀNG");
        jMenuDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDatHangActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDatHang);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 51, 255));
        jMenu2.setText("DANH MỤC");

        jMenuItemNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nv.png"))); // NOI18N
        jMenuItemNV.setText("NHÂN VIÊN");
        jMenuItemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNVActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemNV);

        jMenuItemKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kh.png"))); // NOI18N
        jMenuItemKH.setText("KHÁCH HÀNG");
        jMenuItemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKHActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemKH);

        jMenuItemDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doanhthu.png"))); // NOI18N
        jMenuItemDT.setText("DOANH THU");
        jMenuItemDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDTActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDT);

        jMenuItemHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hd.png"))); // NOI18N
        jMenuItemHD.setText("HÓA ĐƠN");
        jMenuItemHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHDActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemHD);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NCC(1).png"))); // NOI18N
        jMenuItem1.setText("NHÀ XUẤT BẢN");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHHActionPerformed
        // TODO add your handling code here:
         HANGHOA_GUI hangHoaFrame = new HANGHOA_GUI();
          hangHoaFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItemHHActionPerformed

    private void jMenuItemLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoaiActionPerformed
        // TODO add your handling code here:
        LOAI_GUI loai=new LOAI_GUI();
        loai.setVisible(true);
    }//GEN-LAST:event_jMenuItemLoaiActionPerformed

    private void jMenuItemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKHActionPerformed
        // TODO add your handling code here:
        KHACHHANG_GUI khachhang=new KHACHHANG_GUI();
        khachhang.setVisible(true);
    }//GEN-LAST:event_jMenuItemKHActionPerformed

    private void jMenuItemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNVActionPerformed
        // TODO add your handling code here:
      
        
        NHANVIEN_GUI nhanvien=new NHANVIEN_GUI();
        nhanvien.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemNVActionPerformed

    private void jMenuItemDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDTActionPerformed
        // TODO add your handling code here:
        DOANHTHU doanhthu=new DOANHTHU();
        doanhthu.setVisible(true);
    }//GEN-LAST:event_jMenuItemDTActionPerformed

    private void jMenuItemHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHDActionPerformed
        // TODO add your handling code here:
        HOADON_GUI hoadon = new HOADON_GUI(tenNhanVien, maNhanVien);
        hoadon.setVisible(true);
       
    }//GEN-LAST:event_jMenuItemHDActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        NHACC_GUI ncc=new NHACC_GUI();
        ncc.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDatHangActionPerformed
        // TODO add your handling code here:
        DATHANG_GUI dh=new DATHANG_GUI();
        dh.setVisible(true);
    }//GEN-LAST:event_jMenuDatHangActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            dispose(); 
            Login dangnhap = new Login();
            dangnhap.setVisible(true); 
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDatHang;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemDT;
    private javax.swing.JMenuItem jMenuItemHD;
    private javax.swing.JMenuItem jMenuItemHH;
    private javax.swing.JMenuItem jMenuItemKH;
    private javax.swing.JMenuItem jMenuItemLoai;
    private javax.swing.JMenuItem jMenuItemNV;
    private javax.swing.JLabel lblTenNV;
    // End of variables declaration//GEN-END:variables
}
